### ISSUE TITLE
Configure the k8s deployment with a config map that contains the verb level

### ISSUE THREAD

**Issue by jhmarina** [aquarist-labs/s3gw-core#31]
Desiderata is to have the deployment yaml as the follow:

```
containers:
        - name: s3gw
          image: admin:5000/s3gw:latest
          args: ["--rgw-backend-store", $(RGW_BACKEND_STORE), "--debug-rgw", $(DEBUG_RGW)]
          envFrom:
            - configMapRef:
                name: s3gw-config
```

and having a config map containing the values:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: s3gw-config
  namespace: s3gw-system
data:
  RGW_BACKEND_STORE: "dbstore"
  DEBUG_RGW: "1"
```
